### BMI를 계산해서 변수에 저장하고 조건문을 통해 비만, 과체중, 정상, 저체중 여부 판별하는 코드 작성
* BMI = 몸무게 / (키*키)   키 : [m] 몸무게 : kg
* BMI <  18.5 : 저체중 
* 18.5<= BMI <= 23 : 정상
* 23 <= bmi <= 24.9 과체중
* BMI >= 25 : 비만

In [16]:
weight = 59
height = 1.72

BMI = weight / (height * height)

if BMI < 18.5:
    print("저체중")
elif BMI >= 23 and BMI <25:
    print("과체중")
elif BMI >= 25:
    print("비만")
else:
    print("정상")



정상


## 고급 자료형

#### 리스트

* 한 번에 여러 데이터를 연속적으로 저장 가능
* 인덱스 번호를 통해 접근 가능
    * 인덱스 번호는 0번부터 시작 
    

In [28]:
arr = [1, 2,'clap', 4.0, 5, 'clap']
arr, type(arr)


([1, 2, 'clap', 4.0, 5, 'clap'], list)

### 인덱싱
* 앞에서부터는 0번 부터
* 뒤에서부터는 -1번 부터
* 값을 하나만 가져온다

In [29]:
arr[2]

'clap'

### 슬라이싱
* 인덱스가 0 혹은 마지막이라면 생략 가능 (1)
* 뒷번호 앞 까지 슬라이싱 가능 (2)
* 건너 뛰면서 슬라이싱도 가능 (3) - 맨 뒤가 건너뛸 칸의 수

In [30]:
arr[:3]

[1, 2, 'clap']

In [31]:
arr[1:4]

[2, 'clap', 4.0]

In [32]:
arr[0:6:2]

[1, 'clap', 5]

In [33]:
arr = [1, 2, 3, 5, 0, -1]
arr.sort()
arr

[-1, 0, 1, 2, 3, 5]

In [34]:
arr[::-1]

[5, 3, 2, 1, 0, -1]

### 조작
* 길이 확인 (마지막에 필수)
* pop - List의 맨 오른쪽 값을 빼온다
* append - List의 맨 오른쪽에 값을 채워넣는다

In [35]:
len(arr)

6

In [37]:
arr[2] = "end"
arr

[-1, 0, 'end', 2, 3, 5]

In [38]:
arr.pop()

5

In [39]:
arr

[-1, 0, 'end', 2, 3]

In [42]:
arr.append(10)
arr

[-1, 0, 'end', 2, 3, 10, 10, 10]

### Dictionary
* 중괄호 {} 사용
* key : value = item
--> 하나의 쌍으로 값이 저장 

In [43]:
dic = {}
type(dic)

dict

In [44]:
dic = {'title': 'hi', 'year' : 1856, 'author' : 'JW', 'page' : 256}
dic

{'title': 'hi', 'year': 1856, 'author': 'JW', 'page': 256}

In [45]:
dic.items()

dict_items([('title', 'hi'), ('year', 1856), ('author', 'JW'), ('page', 256)])

In [47]:
dic.keys()

dict_keys(['title', 'year', 'author', 'page'])

In [48]:
dic.values()

dict_values(['hi', 1856, 'JW', 256])

In [49]:
len(dic)

4

In [51]:
dic['genre'] = 'fantasy'
dic

{'title': 'hi', 'year': 1856, 'author': 'JW', 'page': 256, 'genre': 'fantasy'}

In [52]:
dic['year'] = 2021
dic

{'title': 'hi', 'year': 2021, 'author': 'JW', 'page': 256, 'genre': 'fantasy'}

In [53]:
dic.pop('title')

'hi'

In [54]:
dic

{'year': 2021, 'author': 'JW', 'page': 256, 'genre': 'fantasy'}

### 튜플(tuple)
* 값을 변경할 수 없는 리스트 (인덱싱만 가능하다)

In [55]:
tup = (1, 4, 2, 5)
tup


(1, 4, 2, 5)

In [56]:
tup[3] = 10

TypeError: 'tuple' object does not support item assignment

In [57]:
tup[3]

5

In [58]:
(246, 10)

(246, 10)

## 반복문 

### while 
* 특정 조건을 만족할 때까지 내부 코드가 반복된다. 

In [59]:
i = 0

while i < 5:
    print(i)
    i += 1

0
1
2
3
4


In [63]:
i = 1

while True:
    if i >= 6:
        break
    print(i, end=' ')
    i += 1 

1 2 3 4 5 

## For 
* for i in range(10):


In [70]:
for i in range(10, -1, -1):
    print(i)

10
9
8
7
6
5
4
3
2
1
0


In [76]:
range(0,10)
list(range(10))


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
for i in range(2,10):
    for j in range(1,10):
        print(f'{i} x {j} = {i * j}')
        

## 반복문 심화

In [79]:
data = [1,2,4,6,7]

for i in data:
    print(i, end=' ')

1 2 4 6 7 

In [81]:
temp = {chr(i): 0 for i in range(65,91)}
temp

{'A': 0,
 'B': 0,
 'C': 0,
 'D': 0,
 'E': 0,
 'F': 0,
 'G': 0,
 'H': 0,
 'I': 0,
 'J': 0,
 'K': 0,
 'L': 0,
 'M': 0,
 'N': 0,
 'O': 0,
 'P': 0,
 'Q': 0,
 'R': 0,
 'S': 0,
 'T': 0,
 'U': 0,
 'V': 0,
 'W': 0,
 'X': 0,
 'Y': 0,
 'Z': 0}

In [83]:
for i in temp.keys():
    print(i, end=' ')

A B C D E F G H I J K L M N O P Q R S T U V W X Y Z 

In [84]:
for i in temp.items():
    print(i, end=' ')

('A', 0) ('B', 0) ('C', 0) ('D', 0) ('E', 0) ('F', 0) ('G', 0) ('H', 0) ('I', 0) ('J', 0) ('K', 0) ('L', 0) ('M', 0) ('N', 0) ('O', 0) ('P', 0) ('Q', 0) ('R', 0) ('S', 0) ('T', 0) ('U', 0) ('V', 0) ('W', 0) ('X', 0) ('Y', 0) ('Z', 0) 

In [85]:
for i in temp.values():
    print(i, end=' ')

0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

In [86]:
data1 = ['a', 'b','c','d']
data2 = [1,2,3,4]

for i,j in zip(data1,data2):
        print(i,j)
        

a 1
b 2
c 3
d 4


In [87]:
for i, j in enumerate(data1):
    print(i,j)

0 a
1 b
2 c
3 d


In [88]:
temp = 1567
str(temp)

'1567'

In [89]:
temp = 1567
for i in str(temp):
    print(i, end = ' ')

1 5 6 7 

In [90]:
list(str(temp))

['1', '5', '6', '7']

In [92]:
a = list(str(temp))
a[0] = '2'
a


['2', '5', '6', '7']

## 사용자 정의 함수

In [94]:
test = [2,3,4,5]
def cal_mean(datas: list):
    cal_sum = 0
    
    for data in datas:
        cal_sum += data 
    res_mean = cal_sum / len(datas)
    
    return res_mean

cal_mean(test)

3.5

# Quiz 

* 양의 정수 x가 주어지고, x의 자릿수의 합으로 나누어 떨어지면 이를 하샤드 수라고 한다. 
* 입력받은 데이터가 하샤드 수인지 판별하는 함수 작성 
* x = 18이라고 하면 1+8=9 --> x/9의 나머지가 0이라면 하샤드 수 
* 나누어 떨어지지 않는다면 하샤드 수가 아니다. 

In [107]:
x = 18
a = list(str(x))
int(a[0])

1

In [112]:
x = input()
a = list(str(x))
x1 = float(a[0])
x2 = float(a[1])

if x / (x1+x2) % 0:
    print("이 수는 하샤드 수 이다.")
else:
    print("이 수는 햐사드 수가 아니다.")

13


TypeError: unsupported operand type(s) for /: 'str' and 'float'

In [111]:
x = input()

13


In [113]:
def quiz(x):
    res = 0
    
    for i in str(x):
        res += int(i)
    return True if x % res == 0 else False 


In [114]:
quiz(18)

True

In [116]:
import numpy as np
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [117]:
print(np.arange(4,3,0.13))

[]


In [119]:
np.random.rand(4,3,7)

array([[[0.72723243, 0.16067484, 0.20339196, 0.91145659, 0.72663997,
         0.49678549, 0.25007834],
        [0.1897903 , 0.72894775, 0.2436516 , 0.90662333, 0.54749999,
         0.30767547, 0.04708826],
        [0.78313067, 0.55200969, 0.89873425, 0.11812348, 0.79271237,
         0.20153093, 0.23551459]],

       [[0.00769943, 0.27107085, 0.85291919, 0.83507868, 0.83273086,
         0.20299518, 0.51017961],
        [0.88907673, 0.6377756 , 0.64210596, 0.96050227, 0.02722894,
         0.64127229, 0.93818418],
        [0.31087822, 0.67694172, 0.83705334, 0.34479748, 0.03162762,
         0.21806386, 0.9265154 ]],

       [[0.21478333, 0.59041454, 0.42146634, 0.96838099, 0.88903512,
         0.3505865 , 0.102961  ],
        [0.39887163, 0.16460821, 0.76326966, 0.95938859, 0.41127877,
         0.75083885, 0.48534751],
        [0.70249057, 0.82292717, 0.75214446, 0.72431952, 0.86664401,
         0.00928596, 0.90934544]],

       [[0.49927857, 0.44970868, 0.51243162, 0.77392447, 0.97471478

In [124]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
arr
a = arr[0:4:3,0:4:3]
a

array([[ 1,  4],
       [13, 16]])

## Replacement
* 넘파이 배열은 인덱싱 및 슬라이싱을 통해 값 변경이 가능하다.


In [125]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [126]:
arr[1,0]=0
arr

array([[ 1,  2,  3,  4],
       [ 0,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [128]:
arr[1][0]=25
arr

array([[ 1,  2,  3,  4],
       [25,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [129]:
arr[arr > 8] = 100
arr

array([[  1,   2,   3,   4],
       [100,   6,   7,   8],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [130]:
arr[:, 2:] = 99
arr

array([[  1,   2,  99,  99],
       [100,   6,  99,  99],
       [100, 100,  99,  99],
       [100, 100,  99,  99]])

In [131]:
arr[2:, :2] = [[-1,-2],[-3,-4]]
arr

array([[  1,   2,  99,  99],
       [100,   6,  99,  99],
       [ -1,  -2,  99,  99],
       [ -3,  -4,  99,  99]])

## Quiz 
다음과 같은 행렬이 주어졌을 때 1로 바꾸기 

In [149]:
Q3 = np.zeros((5,5))
Q3[:,2] = 1
Q3[2,:] = 1
Q3

array([[0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 1., 1., 1., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.]])

# Array Shape

* 넘파이 배열의 상태를 확인하는 방법 
    * 배열이 다차원일 경우, 인덱싱 및 슬라이싱을 통해 해당 차원의 크기를 확인가능하다 .

In [150]:
arr = np.arange(1,17)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [152]:
print(f'행의 길이: {len(arr)}')
print(f'요소의 수: {arr.size}')
print(f'배열의 크기: {arr.shape}')
print(f'배열의 차원: {arr.ndim}')

행의 길이: 16
요소의 수: 16
배열의 크기: (16,)
배열의 차원: 1


* 행의 길이 - len(arr)
* 열의 길이 - len(arr[0])

In [155]:
len(Q3[0])

5

## Reshape

* 예를 들어, 배열의 크기가 (12,)일 경우, (3, 4), (6, 2), (12, 1)로 바꿀 수 있다. 
* -1을 사용하면, 나머지 축에 대해서 알아서 맞춰줌 
    * (-1,4), (6,-1)
    * (-1)
    
   

In [161]:
arr44 = arr.reshape(4,4)
arr44

print(f'행의 길이: {len(arr44)}')
print(f'열의 길이: {len(arr44[0])}')
print(f'배열의 크기: {arr44.shape}')
print(f'배열의 차원: {arr44.ndim}')

행의 길이: 4
열의 길이: 4
배열의 크기: (4, 4)
배열의 차원: 2


In [163]:
arr88 = arr.reshape(8,2)
arr88

print(f'행의 길이: {len(arr88)}')
print(f'열의 길이: {len(arr88[0])}')
print(f'배열의 크기: {arr88.shape}')
print(f'배열의 차원: {arr88.ndim}')
arr88

행의 길이: 8
열의 길이: 2
배열의 크기: (8, 2)
배열의 차원: 2


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [165]:
arr161 = arr.reshape(16,1)
arr161

print(f'행의 길이: {len(arr161)}')
print(f'열의 길이: {len(arr161[0])}')
print(f'배열의 크기: {arr161.shape}')
print(f'배열의 차원: {arr161.ndim}')
arr161

행의 길이: 16
열의 길이: 1
배열의 크기: (16, 1)
배열의 차원: 2


array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16]])

## Quiz. 다음과 같은 길이 45짜리 행렬이 주어졌을 때, 크기를 9x5x1로 바꿔 출력 후, 크기를 확인하는 코드를 아래 셀에 작성하세요.

In [176]:
Q4 = np.zeros(45)
print(Q4.shape)

Q4.reshape(9,5,1).shape

Q4

(45,)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Numpy Operation

* 넘파이 배열은 빠르다. 
    * 반복문을 사용하지 않고 배열의 모든 원소에 대해 연산을 처리할 수 있어서
    * 이를 벡터화 연산이라고 한다. 
* 연산을 위한 조건은 연산하고자 하는 배열의 크기가 모두 동일해야 한다.



### Addition

In [177]:
A = np.arange(1,10,2)
B = np.array([1,1,1,1,1])
np.add(A,B)

array([ 2,  4,  6,  8, 10])

In [178]:
A = np.array([[1,5],
              [4,2]])
B = np.array([[1,3],
              [2,7]])
C = np.array([[4,7],
              [7,4]])
A + B + C 

array([[ 6, 15],
       [13, 13]])

## Subtraction

In [181]:
A = np.array([[1,5],
              [4,2]])
B = np.array([[1,3],
              [2,7]])
C = np.array([[4,7],
              [7,4]])
A - B - C 

array([[-4, -5],
       [-5, -9]])

In [182]:
A = np.array([[1,5],
              [4,2]])
B = np.array([[1,3],
              [2,7]])
C = np.array([[4,7],
              [7,4]])
A - B - C 

array([[  4, 105],
       [ 56,  56]])

In [183]:
A = np.array([[1,5],
              [4,2]])
B = np.array([[1,3],
              [2,7]])
C = np.array([[4,7],
              [7,4]])
A / B / C 

array([[0.25      , 0.23809524],
       [0.28571429, 0.07142857]])

* 넘파이는 크기가 동일하다는 전제 하에 사칙연산이 가능하다. 
* 방법도 실제 사칙연산과 동일하다. 

## Broadcasting 

## Dimension Reduction

* 데이터가 주어졌을 때, 각 성적에 대한 평균, 학생들의 평균 등 행이나 열에 따라 값을 구하는 연산을 차원 축소 연산이라고 한다.
* 행과 열에 대한 계산은 축에 따라 계산되며, 축을 지정하지 않으면 전체를 계산하게 됨
    * 축을 음수로 사용하면 현재 데이터에서 제일 큰 차원이 기준이 된다. 
        axis = -1 --> 3dim, axis = -2 --> 2dim, axis = -3 --> 1dim
    * 3dim 기준 

In [184]:
scores = np.array([[97,78,43,53],
                   [78,65,57,68],
                   [100,98,36,59],
                   [35,50,7,46]])
scores

array([[ 97,  78,  43,  53],
       [ 78,  65,  57,  68],
       [100,  98,  36,  59],
       [ 35,  50,   7,  46]])

In [186]:
students_mean = scores.mean(axis = 0)
students_mean


array([77.5 , 72.75, 35.75, 56.5 ])

In [187]:
students_mean = scores.mean(axis = 0)

print(f'A의 평균: {students_mean[0]}')
print(f'B의 평균: {students_mean[1]}')
print(f'C의 평균: {students_mean[2]}')
print(f'D의 평균: {students_mean[3]}')

A의 평균: 77.5
B의 평균: 72.75
C의 평균: 35.75
D의 평균: 56.5


In [188]:
subject_mean = scores.mean(axis = 1)

print(f'국어의 평균: {subject_mean[0]}')
print(f'영어의 평균: {subject_mean[1]}')
print(f'수학의 평균: {subject_mean[2]}')
print(f'탐구의 평균: {subject_mean[3]}')

국어의 평균: 67.75
영어의 평균: 67.0
수학의 평균: 73.25
탐구의 평균: 34.5


In [191]:
subject_std = scores.std(axis = 1)

print(f'국어의 표준편차: {round(subject_std[0],2)}')
print(f'영어의 표준편차: {round(subject_std[1],3)}')
print(f'수학의 표준편차: {round(subject_std[2],2)}')
print(f'탐구의 표준편차: {round(subject_std[3],1)}')

국어의 표준편차: 21.16
영어의 표준편차: 7.517
수학의 표준편차: 27.01
탐구의 표준편차: 16.8


In [201]:
Q7 = scores.T
Q7

array([[ 97,  78, 100,  35],
       [ 78,  65,  98,  50],
       [ 43,  57,  36,   7],
       [ 53,  68,  59,  46]])

#### Quiz. 위와 같이 전치 행렬이 주어졌을 때, 학생들의 과목 평균 및 표준편차 구하기

* 행 = 학생 (axis = 1)
* 열 = 성적 (axis = 0)

In [202]:
students_mean = scores.T.mean(axis = 1)

print(f'A의 평균: {students_mean[0]}')
print(f'B의 평균: {students_mean[1]}')
print(f'C의 평균: {students_mean[2]}')
print(f'D의 평균: {students_mean[3]}')


A의 평균: 77.5
B의 평균: 72.75
C의 평균: 35.75
D의 평균: 56.5


In [203]:
subject_std = scores.T.std(axis = 0)

print(f'국어의 표준편차: {round(subject_std[0],2)}')
print(f'영어의 표준편차: {round(subject_std[1],3)}')
print(f'수학의 표준편차: {round(subject_std[2],2)}')
print(f'탐구의 표준편차: {round(subject_std[3],2)}')

국어의 표준편차: 21.16
영어의 표준편차: 7.517
수학의 표준편차: 27.01
탐구의 표준편차: 16.8


### argmin & argmax 
* 최소 및 최대값의 위치 = 인덱스 반환
    * 축을 지정하지 않으면 1차원 기준으로 생각해서 인덱스를 반환한다. 
    * 축을 지정하면 각 열 혹은 행에 대해서 순서를 기준으로 위치를 반환한다. 

In [207]:
scores.argmin()
#scores.argmax()

14

In [209]:
scores.argmin(axis=1)

array([2, 2, 2, 2], dtype=int64)

* 최빈값

In [210]:
np.bincount(scores.reshape(-1)).argmax()

78

## Sum()

In [212]:
scores.sum()

970

In [213]:
scores.sum(axis=0)

array([310, 291, 143, 226])

In [214]:
scores.sum(axis=1)

array([271, 268, 293, 138])

### Q8. sum()을 사용하여 과목들의 평균을 구하기 
* 평균 = 데이터의 총합 / 데이터의 수 


In [228]:
scores = np.array([[97,78,43,53],
                   [78,65,57,68],
                   [100,98,36,59],
                   [35,50,7,46]])
scores.sum(axis=1)
a = scores.sum(axis=1)

print(f'국어 평균 : ', a[0]/4 )
print(f'영어 평균 : ', a[1]/4 )
print(f'수학 평균 : ', a[2]/4 )
print(f'탐구 평균 : ', a[3]/4 )


국어 평균 :  67.75
영어 평균 :  67.0
수학 평균 :  73.25
탐구 평균 :  34.5


In [229]:
Q8 = scores.sum(axis=1) / len(scores[0])
Q8

array([67.75, 67.  , 73.25, 34.5 ])