In [2]:
import numpy as np

def Ad(T):
    p = T[:3, 3]
    R = T[:3, :3]
    p_mat = np.array([[0, -p[2], p[1]],
                      [p[2], 0, -p[0]],
                      [-p[1], p[0], 0]])
    Adjoint = np.vstack((np.hstack((R, np.zeros((3, 3)))),
                         np.hstack((p_mat @ R, R))))
    return Adjoint

def skew(w):
    skew_mat = np.array([[0, -w[2], w[1]],
                         [w[2], 0, -w[0]],
                         [-w[1], w[0], 0]], dtype = object)
    return skew_mat

def screw(w, q):
    w_mat = np.array([[0, -w[2], w[1]],
                      [w[2], 0, -w[0]],
                      [-w[1], w[0], 0]], dtype = object)
    v = -np.cross(w, q)
    screw = np.vstack((np.hstack((w_mat, v.reshape(-1, 1))), np.zeros((1, 4))))
    return screw

In [3]:
import numpy as np
import time

from scipy.linalg import expm
from scipy.linalg import logm

q = np.array([0, 0.166, -0.01])

M = np.vstack([np.hstack([np.eye(3), q.reshape(-1, 1)]),
                  np.array([0, 0, 0, 1])])

w1 = np.array([0, 0, 1])
w2 = np.array([1, 0, 0])
w3 = np.array([1, 0, 0])
w4 = np.array([1, 0, 0])
w5 = np.array([0, 0, 1])

q1 = np.array([0, 0, 0])
q2 = np.array([0, 0, 0.073])
q3 = np.array([0, 0.083, 0.073])
q4 = np.array([0, 0.166, 0.073])
q5 = np.array([0, 0.166, 0.033])

v1 = -np.cross(w1, q1)
v2 = -np.cross(w2, q2)
v3 = -np.cross(w3, q3)
v4 = -np.cross(w4, q4)
v5 = -np.cross(w5, q5)

S1 = screw(w1, q1)
S2 = screw(w2, q2)
S3 = screw(w3, q3)
S4 = screw(w4, q4)
S5 = screw(w5, q5)

w1 = w1.reshape(-1,1)
w2 = w2.reshape(-1,1)
w3 = w3.reshape(-1,1)
w4 = w4.reshape(-1,1)
w5 = w5.reshape(-1,1)

v1 = v1.reshape(-1,1)
v2 = v2.reshape(-1,1)
v3 = v3.reshape(-1,1)
v4 = v4.reshape(-1,1)
v5 = v5.reshape(-1,1)

# start position : [0.15, 0.07, 0.0701]
x_d = np.array([0.02, 0.12, 0.07]) 
x_d = x_d.reshape(-1,1)
T_sd = np.vstack([np.hstack([np.eye(3), x_d]),
                  np.array([[0, 0, 0, 1]])])

# th = np.deg2rad([-86.9474, 41.3064, -44.3338, 3.0274, 86.9474])
# th = np.deg2rad([-65.28392204, 47.79348963, -55.77497405, 7.98148442, 65.28392204])
th = np.deg2rad([-81.2715, 53.2575, -43.9620, -9.2955, 81.2715])
th = th.reshape(-1,1)
        
w_b = np.array([1, 1, 1])
w_b = w_b.reshape(-1,1)
v_b = np.array([1, 1, 1])
v_b = v_b.reshape(-1,1)

k = 1
dt = 1

while (np.linalg.norm(w_b) > 0.001 or np.linalg.norm(v_b) > 0.0001):


    T_sb = expm(S1 * th[0]) @ expm(S2 * th[1]) @ expm(S3 * th[2]) @ expm(S4 * th[3]) @ expm(S5 * th[4]) @ M
    T_bs = np.linalg.inv(T_sb)

    AdT_bs = Ad(T_bs)

    Js1 = np.vstack([w1, v1])
    Js2 = Ad(expm(S1 * th[0])) @ np.vstack([w2, v2])
    Js3 = Ad(expm(S1 * th[0]) @ expm(S2 * th[1])) @ np.vstack([w3, v3])
    Js4 = Ad(expm(S1 * th[0]) @ expm(S2 * th[1]) @ expm(S3 * th[2])) @ np.vstack([w4, v4])
    Js5 = Ad(expm(S1 * th[0]) @ expm(S2 * th[1]) @ expm(S3 * th[2]) @ expm(S4 * th[3])) @ np.vstack([w5, v5])
    Js = np.hstack([Js1, Js2, Js3, Js4, Js5])
    Jb = AdT_bs @ Js

    T_bd = T_bs @ T_sd
    V_bmat = logm(T_bd) * 0.1
    w_b = np.array([V_bmat[2, 1], V_bmat[0, 2], V_bmat[1, 0]])
    v_b = V_bmat[:3, 3]
    V_b = np.hstack([w_b, v_b])

    th_center = np.zeros((1, 5))
    th_center[0,2] = -np.pi / 3
    th_center[0,3] = np.pi / 6
    grad_H = np.zeros((1, 5))
    grad_H[0,2] = th[2] - th_center[0,2]
    grad_H[0,3] = th[3] - th_center[0,3]
    grad_H = grad_H.reshape(-1,1)
    gamma = -0.2

    Jvb = np.linalg.pinv(Jb) @ V_b
    Jvb = Jvb.reshape(-1,1)
    dth = Jvb + gamma * (np.eye(5) - np.linalg.pinv(Jb) @ Jb) @ grad_H

    th = th + dth*dt
    th_deg = np.rad2deg(th)
    
    thd = [th_deg[0]+90, th_deg[1], th_deg[2]+90, th_deg[3], -th_deg[4]+90]
    
    k = k + 1
    
    if k == 200:
        break

In [4]:
T_sb

array([[ 1.00000000e+00,  4.44089210e-16,  7.28583860e-17,
         2.06393903e-02],
       [-4.16333634e-16,  1.00000000e+00,  4.99600361e-16,
         1.19301673e-01],
       [-8.75323381e-17, -5.05962350e-16,  1.00000000e+00,
         6.99794326e-02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [93]:
gamma * (np.eye(5) - np.linalg.pinv(Jb)@Jb) @ grad_H

array([[ 2.26063529e-16],
       [-1.42125972e-16],
       [ 2.26449430e-16],
       [-1.31744990e-16],
       [-2.36389130e-16]])

In [5]:
V_b

array([ 5.83420833e-17, -3.30091918e-18,  3.22841602e-17, -6.39390275e-05,
        6.98326794e-05,  2.05674285e-06])