In [19]:
import numpy as np

def Ad(T):
    p = T[:3, 3]
    R = T[:3, :3]
    p_mat = np.array([[0, -p[2], p[1]],
                      [p[2], 0, -p[0]],
                      [-p[1], p[0], 0]])
    Adjoint = np.vstack((np.hstack((R, np.zeros((3, 3)))),
                         np.hstack((p_mat @ R, R))))
    return Adjoint

In [39]:
import numpy as np
from scipy.linalg import expm
from scipy.linalg import logm

q = np.array([0, 0.2004, 0.0068])

M = np.vstack([np.hstack([np.eye(3), q.reshape(-1, 1)]),
                  np.array([0, 0, 0, 1])])

w1 = np.array([0, 0, 1])
w2 = np.array([1, 0, 0])
w3 = np.array([1, 0, 0])
w4 = np.array([1, 0, 0])
w5 = np.array([0, 0, 1])

q1 = np.array([0, 0, 0])
q2 = np.array([0, 0, 0.0701])
q3 = np.array([0, 0.1036, 0.0701])
q4 = np.array([0, 0.2004, 0.0701])
q5 = np.array([0, 0.2004, 0.0391])

v1 = -np.cross(w1, q1)
v2 = -np.cross(w2, q2)
v3 = -np.cross(w3, q3)
v4 = -np.cross(w4, q4)
v5 = -np.cross(w5, q5)

v1 = v1.reshape(-1,1)
v2 = v2.reshape(-1,1)
v3 = v3.reshape(-1,1)
v4 = v4.reshape(-1,1)
v5 = v5.reshape(-1,1)

w_mat1 = np.array([[0, -w1[2], w1[1]],
                   [w1[2], 0, -w1[0]],
                   [-w1[1], w1[0], 0]])
w_mat2 = np.array([[0, -w2[2], w2[1]],
                   [w2[2], 0, -w2[0]],
                   [-w2[1], w2[0], 0]])
w_mat3 = np.array([[0, -w3[2], w3[1]],
                   [w3[2], 0, -w3[0]],
                   [-w3[1], w3[0], 0]])
w_mat4 = np.array([[0, -w4[2], w4[1]],
                   [w4[2], 0, -w4[0]],
                   [-w4[1], w4[0], 0]])
w_mat5 = np.array([[0, -w5[2], w5[1]],
                   [w5[2], 0, -w5[0]],
                   [-w5[1], w5[0], 0]])

S1 = np.vstack([np.hstack([w_mat1, v1.reshape(-1, 1)]),
                np.zeros((1, 4))])
S2 = np.vstack([np.hstack([w_mat2, v2.reshape(-1, 1)]),
                np.zeros((1, 4))])
S3 = np.vstack([np.hstack([w_mat3, v3.reshape(-1, 1)]),
                np.zeros((1, 4))])
S4 = np.vstack([np.hstack([w_mat4, v4.reshape(-1, 1)]), 
                np.zeros((1, 4))])
S5 = np.vstack([np.hstack([w_mat5, v5.reshape(-1, 1)]),
                np.zeros((1, 4))])

w1 = w1.reshape(-1,1)
w2 = w2.reshape(-1,1)
w3 = w3.reshape(-1,1)
w4 = w4.reshape(-1,1)
w5 = w5.reshape(-1,1)

x_d = np.array([0.15, 0.07, 0.0701])
T_sd = np.vstack([np.hstack([np.eye(3), x_d.reshape(-1, 1)]),
                  np.array([[0, 0, 0, 1]])])

th = np.deg2rad([-86.9474, 41.3064, -44.3338, 3.0274, 86.9474])
w_b = np.array([1, 1, 1])
v_b = np.array([1, 1, 1])

k = 1
while (np.linalg.norm(w_b) > 0.001 or np.linalg.norm(v_b) > 0.0001) and k < 200:
    T_sb = expm(S1 * th[0]) @ expm(S2 * th[1]) @ expm(S3 * th[2]) @ expm(S4 * th[3]) @ expm(S5 * th[4]) @ M
    T_bs = np.linalg.inv(T_sb)
    
    AdT_bs = Ad(T_bs)
    
    Js1 = np.vstack([w1, v1])
    Js2 = Ad(expm(S1 * th[0])) @ np.vstack([w2, v2])
    Js3 = Ad(expm(S1 * th[0]) @ expm(S2 * th[1])) @ np.vstack([w3, v3])
    Js4 = Ad(expm(S1 * th[0]) @ expm(S2 * th[1]) @ expm(S3 * th[2])) @ np.vstack([w4, v4])
    Js5 = Ad(expm(S1 * th[0]) @ expm(S2 * th[1]) @ expm(S3 * th[2]) @ expm(S4 * th[3])) @ np.vstack([w5, v5])
    Js = np.hstack([Js1, Js2, Js3, Js4, Js5])
    Jb = AdT_bs @ Js
    
    T_bd = T_bs @ T_sd
    V_bmat = logm(T_bd) * 0.1
    w_b = np.array([V_bmat[2, 1], V_bmat[0, 2], V_bmat[1, 0]])
    v_b = V_bmat[:3, 3]
    V_b = np.hstack([w_b, v_b])
    
    gamma = 0.2
    th_home = np.array([0, 0, 0, 0, 0])
    dth = np.linalg.pinv(Jb) @ V_b + (np.eye(5) - np.linalg.pinv(Jb) @ Jb) * gamma * (th_home - th)
    
    th = th + dth
    th_deg = np.rad2deg(th)
    
    k = k + 1
    
                

ValueError: operands could not be broadcast together with shapes (4,4) (5,) 

In [30]:
w1.reshape(np.array([0, 0, 1]))
w2 = np.array([1, 0, 0])
w3 = np.array([1, 0, 0])
w4 = np.array([1, 0, 0])
w5 = np.array([0, 0, 1])

ValueError: cannot reshape array of size 3 into shape (0,0,1)

 Matlab에서 Python code로 변환

In [117]:
import numpy as np

def Ad(T):
    p = T[:3, 3]
    R = T[:3, :3]
    p_mat = np.array([[0, -p[2], p[1]],
                      [p[2], 0, -p[0]],
                      [-p[1], p[0], 0]])
    Adjoint = np.vstack((np.hstack((R, np.zeros((3, 3)))),
                         np.hstack((p_mat @ R, R))))
    return Adjoint

def skew(w):
    skew_mat = np.array([[0, -w[2], w[1]],
                         [w[2], 0, -w[0]],
                         [-w[1], w[0], 0]], dtype = object)
    return skew_mat

In [118]:
w1 = np.array([0, 0, 1])
w_mat1 = skew(w1)
w2 = np.array([1, 0, 0])
w_mat2 = skew(w2)


In [115]:
w_mat2

array([[ 0,  0,  0],
       [ 0,  0, -1],
       [ 0,  1,  0]])

In [119]:
import numpy as np
from scipy.linalg import expm
from scipy.linalg import logm

q = np.array([0, 0.2004, 0.0068])

M = np.vstack([np.hstack([np.eye(3), q.reshape(-1, 1)]),
                  np.array([0, 0, 0, 1])])

w1 = np.array([0, 0, 1])
w2 = np.array([1, 0, 0])
w3 = np.array([1, 0, 0])
w4 = np.array([1, 0, 0])
w5 = np.array([0, 0, 1])

q1 = np.array([0, 0, 0])
q2 = np.array([0, 0, 0.0701])
q3 = np.array([0, 0.1036, 0.0701])
q4 = np.array([0, 0.2004, 0.0701])
q5 = np.array([0, 0.2004, 0.0391])

v1 = -np.cross(w1, q1)
v2 = -np.cross(w2, q2)
v3 = -np.cross(w3, q3)
v4 = -np.cross(w4, q4)
v5 = -np.cross(w5, q5)

w1 = w1.reshape(-1,1)
w2 = w2.reshape(-1,1)
w3 = w3.reshape(-1,1)
w4 = w4.reshape(-1,1)
w5 = w5.reshape(-1,1)

v1 = v1.reshape(-1,1)
v2 = v2.reshape(-1,1)
v3 = v3.reshape(-1,1)
v4 = v4.reshape(-1,1)
v5 = v5.reshape(-1,1)

w_mat1 = skew(w1)
w_mat2 = skew(w2)
w_mat3 = skew(w3)
w_mat4 = skew(w4)
w_mat5 = skew(w5)

S1 = np.vstack([np.hstack([w_mat1, v1.reshape(-1, 1)]),
                np.zeros((1, 4))])
S2 = np.vstack([np.hstack([w_mat2, v2.reshape(-1, 1)]),
                np.zeros((1, 4))])
S3 = np.vstack([np.hstack([w_mat3, v3.reshape(-1, 1)]),
                np.zeros((1, 4))])
S4 = np.vstack([np.hstack([w_mat4, v4.reshape(-1, 1)]), 
                np.zeros((1, 4))])
S5 = np.vstack([np.hstack([w_mat5, v5.reshape(-1, 1)]),
                np.zeros((1, 4))])

x_d = np.array([0.15, 0.07, 0.0701])
x_d = x_d.reshape(-1,1)
T_sd = np.vstack([np.hstack([np.eye(3), x_d]),
                  np.array([[0, 0, 0, 1]])])

th = np.deg2rad([-86.9474, 41.3064, -44.3338, 3.0274, 86.9474])
w_b = np.array([1, 1, 1])
w_b = w_b.reshape(-1,1)
v_b = np.array([1, 1, 1])
v_b = v_b.reshape(-1,1)

k = 1
while (np.linalg.norm(w_b) > 0.001 or np.linalg.norm(v_b) > 0.0001) and k < 200:


    T_sb = expm(S1 * th[0]) @ expm(S2 * th[1]) @ expm(S3 * th[2]) @ expm(S4 * th[3]) @ expm(S5 * th[4]) @ M
    T_bs = np.linalg.inv(T_sb)

    AdT_bs = Ad(T_bs)

    Js1 = np.vstack([w1, v1])
    Js2 = Ad(expm(S1 * th[0])) @ np.vstack([w2, v2])
    Js3 = Ad(expm(S1 * th[0]) @ expm(S2 * th[1])) @ np.vstack([w3, v3])
    Js4 = Ad(expm(S1 * th[0]) @ expm(S2 * th[1]) @ expm(S3 * th[2])) @ np.vstack([w4, v4])
    Js5 = Ad(expm(S1 * th[0]) @ expm(S2 * th[1]) @ expm(S3 * th[2]) @ expm(S4 * th[3])) @ np.vstack([w5, v5])
    Js = np.hstack([Js1, Js2, Js3, Js4, Js5])
    Jb = AdT_bs @ Js

    T_bd = T_bs @ T_sd
    V_bmat = logm(T_bd) * 0.1
    w_b = np.array([V_bmat[2, 1], V_bmat[0, 2], V_bmat[1, 0]])
    v_b = V_bmat[:3, 3]
    V_b = np.hstack([w_b, v_b])

    gamma = 0.2
    th_home = np.array([0, 0, 0, 0, 0])
    dth = np.linalg.pinv(Jb) @ V_b + gamma * (np.eye(5) - np.linalg.pinv(Jb) @ Jb) @ (th_home - th)

    th = th + dth
    th_deg = np.rad2deg(th)

    k = k + 1
    
    T_sb



In [120]:
th_deg

array([-65.28392204,  47.79348963, -55.77497405,   7.98148442,
        65.28392204])

In [105]:
T_sb

array([[ 1.00000000e+00,  2.22044605e-16, -1.38777878e-16,
         1.50337264e-01],
       [-1.11022302e-16,  1.00000000e+00, -9.02056208e-17,
         6.90922278e-02],
       [ 5.04393618e-17,  2.31809984e-17,  1.00000000e+00,
         7.00983004e-02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])